In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [30]:
A = np.array(([1,2,3],[4,5,6],[7,8,9]))
B = np.transpose(A)
C = A @ A
D = A @ B
E = B.T

print(A)
print(B)
print(C)
print(D)
print(E)

3
[[[list([2]) list([3]) 1]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]



---
# VIDEO: Computing rank: theory and practice
---


In [6]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank=' + str(ra))


# set last column to be repeat of penultimate column
B = A
B[m-1,:] = B[m-2,:]
rb = np.linalg.matrix_rank(B)
print(B)
print('rank=' + str(rb))

rank=4
[[ 0.15446849  1.04842362 -1.96741625 -0.80071194  0.9074539   0.25164153]
 [ 0.06878494 -2.21212821  0.24347385  1.78747584  1.50629094  0.012236  ]
 [ 1.07001738 -1.11369682  2.39103653  0.40549178 -1.06297632  1.15757725]
 [ 1.07001738 -1.11369682  2.39103653  0.40549178 -1.06297632  1.15757725]]
rank=3


In [29]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,m-1] = A[:,m-2]

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4



---
# VIDEO: Rank of A^TA and AA^T
---


In [45]:

# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = np.matrix.transpose(A)@A
AAt = A@np.matrix.transpose(A)

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))


AtA: 3x3, rank=3
AAt: 14x14, rank=3



---
# VIDEO: Making a matrix full-rank by "shifting"
---


In [47]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*np.matrix.transpose(A)@A )

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))


rank(w/o shift) = 29
rank(with shift) = 30
